import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]
[window] 
opacity = 0.98
blur = true

[font]
size = 15.0

[font.bold]
family = "GoMonoNerdFont"
style = "Bold"

[font.bold_italic]
family = "GoMonoNerdFont"
style = "Bold Italic"

[font.italic]
family = "GoMonoNerdFont"
style = "Italic"

[font.normal]
family = "GoMonoNerdFont"
style = "Regular"
