import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]
[window] 
opacity = 0.9
blur = true

[font]
size = 10.0

[font.bold]
family = "0xProtoNerdFontMono"
style = "Bold"

[font.bold_italic]
family = "0xProtoNerdFontMono"
style = "Bold Italic"

[font.italic]
family = "0xProtoNerdFontMono"
style = "Italic"

[font.normal]
family = "0xProtoNerdFontMono"
style = "Regular"
